// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGAD9M-TT05iFHOt7A7re7Q7Y0YHk5N94',
    appId: '1:161225043681:web:5baf6875af53d8e76351a0',
    messagingSenderId: '161225043681',
    projectId: 'instagram-clone-79565',
    authDomain: 'instagram-clone-79565.firebaseapp.com',
    storageBucket: 'instagram-clone-79565.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpAZTC9ur_jDYV-11hrTXEJ2v9GqTs5ps',
    appId: '1:161225043681:android:ea8bebceed0ce7436351a0',
    messagingSenderId: '161225043681',
    projectId: 'instagram-clone-79565',
    storageBucket: 'instagram-clone-79565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuzavme5oDPpC3Fl1JTXbty8-44-35F-I',
    appId: '1:161225043681:ios:09773c28a2b9c47f6351a0',
    messagingSenderId: '161225043681',
    projectId: 'instagram-clone-79565',
    storageBucket: 'instagram-clone-79565.appspot.com',
    iosBundleId: 'com.example.instagramCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuzavme5oDPpC3Fl1JTXbty8-44-35F-I',
    appId: '1:161225043681:ios:6b13365cc0420ffc6351a0',
    messagingSenderId: '161225043681',
    projectId: 'instagram-clone-79565',
    storageBucket: 'instagram-clone-79565.appspot.com',
    iosBundleId: 'com.example.instagramCloneApp.RunnerTests',
  );
}
